spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/Fitness
    username: postgres
    password: Golu@1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
